import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useQueryClient } from '@tanstack/react-query';
import { Check, FileText, CheckCircle } from 'lucide-react-native';
import { Button, Card, CardContent } from '@/components/ui';
import { apiClient } from '@/api/client';
import { API_ENDPOINTS } from '@/config/api';
import { colors, spacing, fontSize, fontWeight, borderRadius } from '@/config/theme';

const AGREEMENT_SECTIONS = [
  {
    title: '1. Investment Terms',
    content: `By participating in the SuberCraftex Investment Program, you agree to invest funds that will be allocated to products or equipment (machines). Your returns will be based on the sales performance of products and the usage/profits generated by equipment you have invested in.`,
  },
  {
    title: '2. Product Profit Distribution',
    content: `For product investments, when a product is sold and profit is generated, the profit is split equally: 50% goes to the investors who funded the product, and 50% goes to SuberCraftex. Your share of the 50% investor portion is proportional to your investment in that product.`,
  },
  {
    title: '3. Equipment/Machine Profit Distribution',
    content: `For equipment or machine investments, profits generated from the machine's operations are distributed as follows: 50% goes to SuberCraftex, and 50% is distributed among all investors who contributed to the purchase of that equipment. Your share is calculated based on your stake (percentage of contribution) in the equipment purchase.`,
  },
  {
    title: '4. Withdrawal Terms',
    content: `You may withdraw your funds through four methods: Cash Withdrawal (subject to available cash balance), Profit Withdrawal, Product Withdrawal (receive products at cost price), or Equipment Share Exit (sell your equipment stake).`,
  },
  {
    title: '5. Risk Disclosure',
    content: `All investments carry risk. While we strive to protect your capital through tangible asset allocation, returns are not guaranteed. Past performance does not indicate future results. Product sales and equipment profitability may vary.`,
  },
  {
    title: '6. KYC Requirements',
    content: `You must complete identity verification (KYC) before making deposits or withdrawals. This is required by law to prevent fraud and money laundering.`,
  },
  {
    title: '7. Fees and Charges',
    content: `Mobile money deposits may incur transaction fees from the payment provider. These charges are deducted before crediting your account. There are no hidden fees from SuberCraftex.`,
  },
  {
    title: '8. Account Security',
    content: `You are responsible for maintaining the security of your account. Do not share your login credentials. Report any suspicious activity immediately.`,
  },
  {
    title: '9. Termination',
    content: `Either party may terminate this agreement with 30 days notice. Upon termination, all outstanding balances will be settled according to the withdrawal terms.`,
  },
];

export default function AgreementScreen() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [isLoading, setIsLoading] = useState(false);
  const [isFetchingStatus, setIsFetchingStatus] = useState(true);
  const [agreementAlreadyAccepted, setAgreementAlreadyAccepted] = useState(false);
  const [accepted, setAccepted] = useState(false);

  useEffect(() => {
    checkAgreementStatus();
  }, []);

  const checkAgreementStatus = async () => {
    try {
      const response = await apiClient.get(API_ENDPOINTS.investor.me);
      if (response.data.agreementAccepted) {
        setAgreementAlreadyAccepted(true);
      }
    } catch (error) {
      // If error, assume not accepted yet
    } finally {
      setIsFetchingStatus(false);
    }
  };

  const handleAccept = async () => {
    if (!accepted) {
      Alert.alert(
        'Agreement Required',
        'Please read and accept the investment agreement to continue.'
      );
      return;
    }

    setIsLoading(true);
    try {
      await apiClient.post(API_ENDPOINTS.investor.acceptAgreement);
      // Invalidate and refetch the investor cache so dashboard gets fresh data
      await queryClient.invalidateQueries({ queryKey: ['investor', 'me'] });
      await queryClient.refetchQueries({ queryKey: ['investor', 'me'] });
      Alert.alert(
        'Welcome!',
        'You are now registered as an investor. You can start making deposits once your KYC is approved.',
        [{ text: 'Go to Dashboard', onPress: () => router.replace('/(investor)/dashboard') }]
      );
    } catch (error: any) {
      Alert.alert(
        'Error',
        error.response?.data?.error || 'Failed to accept agreement. Please try again.'
      );
    } finally {
      setIsLoading(false);
    }
  };

  // Show loading while fetching status
  if (isFetchingStatus) {
    return (
      <SafeAreaView style={styles.container} edges={['bottom']}>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={colors.primary.DEFAULT} />
          <Text style={styles.loadingText}>Loading...</Text>
        </View>
      </SafeAreaView>
    );
  }

  // Show already accepted screen
  if (agreementAlreadyAccepted) {
    return (
      <SafeAreaView style={styles.container} edges={['bottom']}>
        <View style={styles.acceptedContainer}>
          <View style={styles.acceptedIconContainer}>
            <CheckCircle size={64} color={colors.success.DEFAULT} />
          </View>
          <Text style={styles.acceptedTitle}>Agreement Accepted</Text>
          <Text style={styles.acceptedDescription}>
            You have already accepted the investment agreement. You can now access your investor dashboard.
          </Text>
          <View style={styles.acceptedActions}>
            <Button
              title="Go to Dashboard"
              onPress={() => router.replace('/(investor)/dashboard')}
              fullWidth
              size="lg"
            />
          </View>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container} edges={['bottom']}>
      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.iconContainer}>
            <FileText size={32} color={colors.primary.DEFAULT} />
          </View>
          <Text style={styles.title}>Investment Agreement</Text>
          <Text style={styles.subtitle}>
            Please read the following terms carefully before proceeding
          </Text>
        </View>

        {/* Agreement Content */}
        <View style={styles.content}>
          {AGREEMENT_SECTIONS.map((section, index) => (
            <Card key={index} style={styles.sectionCard} variant="outlined">
              <CardContent>
                <Text style={styles.sectionTitle}>{section.title}</Text>
                <Text style={styles.sectionContent}>{section.content}</Text>
              </CardContent>
            </Card>
          ))}
        </View>

        {/* Accept Checkbox */}
        <View style={styles.acceptSection}>
          <TouchableOpacity
            style={styles.checkbox}
            onPress={() => setAccepted(!accepted)}
          >
            <View
              style={[
                styles.checkboxBox,
                accepted && styles.checkboxBoxChecked,
              ]}
            >
              {accepted && <Check size={16} color={colors.white} />}
            </View>
            <Text style={styles.checkboxLabel}>
              I have read, understood, and agree to the Investment Agreement and
              Terms of Service
            </Text>
          </TouchableOpacity>
        </View>
      </ScrollView>

      {/* Bottom Action */}
      <View style={styles.bottomAction}>
        <Button
          title="Accept & Continue"
          onPress={handleAccept}
          loading={isLoading}
          disabled={!accepted}
          fullWidth
          size="lg"
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray[50],
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: spacing.md,
    fontSize: fontSize.base,
    color: colors.gray[600],
  },
  acceptedContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  acceptedIconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.success[50],
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  acceptedTitle: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.gray[900],
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  acceptedDescription: {
    fontSize: fontSize.base,
    color: colors.gray[600],
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: spacing.xl,
  },
  acceptedActions: {
    width: '100%',
  },
  header: {
    alignItems: 'center',
    padding: spacing.xl,
    backgroundColor: colors.white,
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  title: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.gray[900],
    marginBottom: spacing.xs,
  },
  subtitle: {
    fontSize: fontSize.sm,
    color: colors.gray[600],
    textAlign: 'center',
  },
  content: {
    padding: spacing.lg,
  },
  sectionCard: {
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.gray[900],
    marginBottom: spacing.sm,
  },
  sectionContent: {
    fontSize: fontSize.sm,
    color: colors.gray[600],
    lineHeight: 22,
  },
  acceptSection: {
    padding: spacing.lg,
    paddingTop: 0,
  },
  checkbox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  checkboxBox: {
    width: 24,
    height: 24,
    borderRadius: borderRadius.sm,
    borderWidth: 2,
    borderColor: colors.gray[300],
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
    marginTop: 2,
  },
  checkboxBoxChecked: {
    backgroundColor: colors.primary.DEFAULT,
    borderColor: colors.primary.DEFAULT,
  },
  checkboxLabel: {
    flex: 1,
    fontSize: fontSize.sm,
    color: colors.gray[700],
    lineHeight: 22,
  },
  bottomAction: {
    padding: spacing.lg,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.gray[200],
  },
});
